/* ═══════════════════════════════════════════════
   CITY DATA — RE Research 2026
   All values are 2026 market estimates
═══════════════════════════════════════════════ */

const CITIES = [
  {
    id: 'bangalore',
    name: 'Bangalore',
    tier: 1,
    state: 'Karnataka',
    avgPriceSqft: '₹9,260',
    avgFlat2BHK: 5500000,
    yieldRange: '3–6%',
    yieldMid: 3.5,
    yieldMin: 3, yieldMax: 6,
    stampDuty: 5.6,
    registration: 1,
    loanRate: 8.5,
    appreciation: 8,
    demandLevel: 'Very High',
    demandNote: 'IT corridor driven',
    avgRent2BHK: 28000,
    zones: [
      { name: 'Whitefield', yield: '6–9%', appreciation: 'High', yieldMid: 7.5 },
      { name: 'Sarjapur Road', yield: '6–8%', appreciation: 'High', yieldMid: 7 },
      { name: 'Electronic City', yield: '6–8.5%', appreciation: 'Med-High', yieldMid: 7.2 },
      { name: 'Koramangala', yield: '4–7%', appreciation: 'Stable', yieldMid: 5.5 },
      { name: 'Hebbal/Yelahanka', yield: '6–8.5%', appreciation: 'Very High', yieldMid: 7.2 },
      { name: 'Indiranagar', yield: '2.5–4%', appreciation: 'Wealth Pres.', yieldMid: 3.2 },
    ]
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    tier: 1,
    state: 'Maharashtra',
    avgPriceSqft: '₹22,400',
    avgFlat2BHK: 12000000,
    yieldRange: '2–3%',
    yieldMid: 2.4,
    yieldMin: 2, yieldMax: 3.5,
    stampDuty: 5,
    registration: 1,
    loanRate: 8.5,
    appreciation: 6,
    demandLevel: 'Very High',
    demandNote: 'Financial capital demand',
    avgRent2BHK: 45000,
    zones: [
      { name: 'Powai', yield: '2.5–4%', appreciation: 'High', yieldMid: 3.2 },
      { name: 'Thane', yield: '3–5%', appreciation: 'Med-High', yieldMid: 4 },
      { name: 'Navi Mumbai', yield: '3.5–5.5%', appreciation: 'High', yieldMid: 4.5 },
      { name: 'Andheri', yield: '2–3.5%', appreciation: 'Stable', yieldMid: 2.7 },
      { name: 'Bandra', yield: '1.5–2.5%', appreciation: 'Premium', yieldMid: 2 },
      { name: 'Panvel', yield: '4–6%', appreciation: 'High', yieldMid: 5 },
    ]
  },
  {
    id: 'delhi',
    name: 'Delhi NCR',
    tier: 1,
    state: 'Delhi/UP/HR',
    avgPriceSqft: '₹8,800',
    avgFlat2BHK: 7500000,
    yieldRange: '2.5–4%',
    yieldMid: 2.8,
    yieldMin: 2.5, yieldMax: 4,
    stampDuty: 6,
    registration: 1,
    loanRate: 8.5,
    appreciation: 7,
    demandLevel: 'High',
    demandNote: 'Government + corporate',
    avgRent2BHK: 25000,
    zones: [
      { name: 'Gurgaon (Cyber City)', yield: '3–5%', appreciation: 'High', yieldMid: 4 },
      { name: 'Noida Expressway', yield: '3.5–5.5%', appreciation: 'High', yieldMid: 4.5 },
      { name: 'Dwarka Expressway', yield: '3–5%', appreciation: 'Very High', yieldMid: 4 },
      { name: 'South Delhi', yield: '2–3%', appreciation: 'Stable', yieldMid: 2.5 },
      { name: 'Greater Noida', yield: '4–6%', appreciation: 'Med', yieldMid: 5 },
      { name: 'Faridabad', yield: '3.5–5%', appreciation: 'Med', yieldMid: 4.2 },
    ]
  },
  {
    id: 'pune',
    name: 'Pune',
    tier: 1,
    state: 'Maharashtra',
    avgPriceSqft: '₹7,200',
    avgFlat2BHK: 5000000,
    yieldRange: '3–5%',
    yieldMid: 3.8,
    yieldMin: 3, yieldMax: 5,
    stampDuty: 5,
    registration: 1,
    loanRate: 8.5,
    appreciation: 8,
    demandLevel: 'High',
    demandNote: 'IT + education hub',
    avgRent2BHK: 22000,
    zones: [
      { name: 'Hinjewadi', yield: '4–6%', appreciation: 'Very High', yieldMid: 5 },
      { name: 'Wakad', yield: '4–6%', appreciation: 'High', yieldMid: 5 },
      { name: 'Kharadi', yield: '4–7%', appreciation: 'High', yieldMid: 5.5 },
      { name: 'Hadapsar', yield: '3.5–5.5%', appreciation: 'Med-High', yieldMid: 4.5 },
      { name: 'Baner', yield: '3–5%', appreciation: 'Stable', yieldMid: 4 },
      { name: 'Viman Nagar', yield: '3–4.5%', appreciation: 'Stable', yieldMid: 3.7 },
    ]
  },
  {
    id: 'hyderabad',
    name: 'Hyderabad',
    tier: 1,
    state: 'Telangana',
    avgPriceSqft: '₹6,800',
    avgFlat2BHK: 5200000,
    yieldRange: '3–5%',
    yieldMid: 3.5,
    yieldMin: 3, yieldMax: 5,
    stampDuty: 4,
    registration: 0.5,
    loanRate: 8.5,
    appreciation: 9,
    demandLevel: 'Very High',
    demandNote: 'HITEC City expansion',
    avgRent2BHK: 24000,
    zones: [
      { name: 'HITEC City', yield: '4–6%', appreciation: 'Very High', yieldMid: 5 },
      { name: 'Gachibowli', yield: '4–7%', appreciation: 'Very High', yieldMid: 5.5 },
      { name: 'Kondapur', yield: '3.5–5.5%', appreciation: 'High', yieldMid: 4.5 },
      { name: 'Financial District', yield: '4–6%', appreciation: 'Very High', yieldMid: 5 },
      { name: 'Kukatpally', yield: '3.5–5%', appreciation: 'High', yieldMid: 4.2 },
      { name: 'Jubilee Hills', yield: '2.5–4%', appreciation: 'Premium', yieldMid: 3.2 },
    ]
  },
  {
    id: 'chennai',
    name: 'Chennai',
    tier: 1,
    state: 'Tamil Nadu',
    avgPriceSqft: '₹6,400',
    avgFlat2BHK: 4800000,
    yieldRange: '3.5–5%',
    yieldMid: 4,
    yieldMin: 3.5, yieldMax: 5,
    stampDuty: 7,
    registration: 4,
    loanRate: 8.5,
    appreciation: 7,
    demandLevel: 'High',
    demandNote: 'Manufacturing + IT',
    avgRent2BHK: 20000,
    zones: [
      { name: 'OMR (Old Mahabalipuram)', yield: '4–6%', appreciation: 'High', yieldMid: 5 },
      { name: 'Porur', yield: '3.5–5.5%', appreciation: 'Med-High', yieldMid: 4.5 },
      { name: 'Sholinganallur', yield: '4–6.5%', appreciation: 'High', yieldMid: 5.2 },
      { name: 'Anna Nagar', yield: '3–4.5%', appreciation: 'Stable', yieldMid: 3.7 },
      { name: 'Velachery', yield: '3.5–5%', appreciation: 'Med-High', yieldMid: 4.2 },
      { name: 'Adyar', yield: '2.5–3.5%', appreciation: 'Premium', yieldMid: 3 },
    ]
  },
  {
    id: 'kolkata',
    name: 'Kolkata',
    tier: 1,
    state: 'West Bengal',
    avgPriceSqft: '₹5,200',
    avgFlat2BHK: 4200000,
    yieldRange: '3–5%',
    yieldMid: 3.8,
    yieldMin: 3, yieldMax: 5,
    stampDuty: 6,
    registration: 1,
    loanRate: 8.5,
    appreciation: 5,
    demandLevel: 'Medium',
    demandNote: 'Steady organic demand',
    avgRent2BHK: 18000,
    zones: [
      { name: 'New Town/Rajarhat', yield: '4–6%', appreciation: 'High', yieldMid: 5 },
      { name: 'Salt Lake', yield: '3–5%', appreciation: 'Med', yieldMid: 4 },
      { name: 'EM Bypass', yield: '3.5–5.5%', appreciation: 'Med-High', yieldMid: 4.5 },
      { name: 'Ballygunge', yield: '2.5–4%', appreciation: 'Stable', yieldMid: 3.2 },
      { name: 'Gariahat', yield: '3–4.5%', appreciation: 'Stable', yieldMid: 3.7 },
      { name: 'Behala', yield: '4–5.5%', appreciation: 'Med', yieldMid: 4.7 },
    ]
  },
  {
    id: 'ahmedabad',
    name: 'Ahmedabad',
    tier: 1,
    state: 'Gujarat',
    avgPriceSqft: '₹5,600',
    avgFlat2BHK: 3800000,
    yieldRange: '3.5–5.5%',
    yieldMid: 4.2,
    yieldMin: 3.5, yieldMax: 5.5,
    stampDuty: 4.9,
    registration: 1,
    loanRate: 8.25,
    appreciation: 7,
    demandLevel: 'High',
    demandNote: 'GIFT City + manufacturing',
    avgRent2BHK: 16000,
    zones: [
      { name: 'GIFT City', yield: '5–8%', appreciation: 'Very High', yieldMid: 6.5 },
      { name: 'SG Highway', yield: '4–6%', appreciation: 'High', yieldMid: 5 },
      { name: 'Prahlad Nagar', yield: '3.5–5%', appreciation: 'Med-High', yieldMid: 4.2 },
      { name: 'Bopal', yield: '4–5.5%', appreciation: 'High', yieldMid: 4.7 },
      { name: 'Satellite', yield: '3–4.5%', appreciation: 'Stable', yieldMid: 3.7 },
      { name: 'Chandkheda', yield: '4–6%', appreciation: 'High', yieldMid: 5 },
    ]
  },
  {
    id: 'jaipur',
    name: 'Jaipur',
    tier: 2,
    state: 'Rajasthan',
    avgPriceSqft: '₹4,200',
    avgFlat2BHK: 3000000,
    yieldRange: '4–6%',
    yieldMid: 4.8,
    yieldMin: 4, yieldMax: 6,
    stampDuty: 5,
    registration: 1,
    loanRate: 8.75,
    appreciation: 7,
    demandLevel: 'High',
    demandNote: 'Tourism + expanding IT',
    avgRent2BHK: 15000,
    zones: [
      { name: 'Mansarovar', yield: '4.5–6.5%', appreciation: 'High', yieldMid: 5.5 },
      { name: 'Vaishali Nagar', yield: '4–6%', appreciation: 'Med-High', yieldMid: 5 },
      { name: 'Malviya Nagar', yield: '4–5.5%', appreciation: 'Med-High', yieldMid: 4.7 },
      { name: 'Tonk Road', yield: '5–7%', appreciation: 'High', yieldMid: 6 },
      { name: 'Jagatpura', yield: '5–7%', appreciation: 'High', yieldMid: 6 },
      { name: 'Ajmer Road', yield: '4.5–6%', appreciation: 'Med', yieldMid: 5.2 },
    ]
  },
  {
    id: 'indore',
    name: 'Indore',
    tier: 2,
    state: 'Madhya Pradesh',
    avgPriceSqft: '₹3,800',
    avgFlat2BHK: 2800000,
    yieldRange: '4.5–6.5%',
    yieldMid: 5.2,
    yieldMin: 4.5, yieldMax: 6.5,
    stampDuty: 7.5,
    registration: 3,
    loanRate: 8.75,
    appreciation: 8,
    demandLevel: 'High',
    demandNote: 'Cleanest city + growth hub',
    avgRent2BHK: 13000,
    zones: [
      { name: 'Vijay Nagar', yield: '5–7%', appreciation: 'High', yieldMid: 6 },
      { name: 'Scheme 54', yield: '4.5–6.5%', appreciation: 'Med-High', yieldMid: 5.5 },
      { name: 'AB Road', yield: '5–7%', appreciation: 'High', yieldMid: 6 },
      { name: 'Super Corridor', yield: '5.5–8%', appreciation: 'Very High', yieldMid: 6.7 },
      { name: 'Palasia', yield: '4–5.5%', appreciation: 'Stable', yieldMid: 4.7 },
      { name: 'Bicholi Mardana', yield: '5–7%', appreciation: 'High', yieldMid: 6 },
    ]
  },
  {
    id: 'lucknow',
    name: 'Lucknow',
    tier: 2,
    state: 'Uttar Pradesh',
    avgPriceSqft: '₹4,100',
    avgFlat2BHK: 3200000,
    yieldRange: '4.5–6%',
    yieldMid: 5,
    yieldMin: 4.5, yieldMax: 6,
    stampDuty: 7,
    registration: 1,
    loanRate: 8.75,
    appreciation: 7,
    demandLevel: 'High',
    demandNote: 'State capital expansion',
    avgRent2BHK: 14000,
    zones: [
      { name: 'Gomti Nagar', yield: '4.5–6%', appreciation: 'High', yieldMid: 5.2 },
      { name: 'Aliganj', yield: '4.5–6.5%', appreciation: 'Med-High', yieldMid: 5.5 },
      { name: 'Hazratganj', yield: '3.5–5%', appreciation: 'Stable', yieldMid: 4.2 },
      { name: 'Sushant Golf City', yield: '5–7%', appreciation: 'High', yieldMid: 6 },
      { name: 'Vikas Nagar', yield: '5–7%', appreciation: 'Med-High', yieldMid: 6 },
      { name: 'Indira Nagar', yield: '4.5–6%', appreciation: 'Med-High', yieldMid: 5.2 },
    ]
  },
  {
    id: 'nagpur',
    name: 'Nagpur',
    tier: 2,
    state: 'Maharashtra',
    avgPriceSqft: '₹3,600',
    avgFlat2BHK: 2600000,
    yieldRange: '4.5–6.5%',
    yieldMid: 5.5,
    yieldMin: 4.5, yieldMax: 6.5,
    stampDuty: 5,
    registration: 1,
    loanRate: 8.75,
    appreciation: 6,
    demandLevel: 'Medium',
    demandNote: 'Zero mile city logistics',
    avgRent2BHK: 12000,
    zones: [
      { name: 'Wardha Road', yield: '5–7%', appreciation: 'High', yieldMid: 6 },
      { name: 'Sitabuldi', yield: '4–5.5%', appreciation: 'Stable', yieldMid: 4.7 },
      { name: 'Dharampeth', yield: '4.5–6%', appreciation: 'Med-High', yieldMid: 5.2 },
      { name: 'MIHAN', yield: '5.5–8%', appreciation: 'Very High', yieldMid: 6.7 },
      { name: 'Amravati Road', yield: '4.5–6.5%', appreciation: 'Med-High', yieldMid: 5.5 },
      { name: 'Hingna Road', yield: '5–7%', appreciation: 'High', yieldMid: 6 },
    ]
  },
  {
    id: 'surat',
    name: 'Surat',
    tier: 2,
    state: 'Gujarat',
    avgPriceSqft: '₹4,400',
    avgFlat2BHK: 3200000,
    yieldRange: '4–6%',
    yieldMid: 4.8,
    yieldMin: 4, yieldMax: 6,
    stampDuty: 4.9,
    registration: 1,
    loanRate: 8.25,
    appreciation: 7,
    demandLevel: 'High',
    demandNote: 'Diamond + textile trade',
    avgRent2BHK: 13500,
    zones: [
      { name: 'Vesu', yield: '4.5–6.5%', appreciation: 'High', yieldMid: 5.5 },
      { name: 'Pal', yield: '4–6%', appreciation: 'Med-High', yieldMid: 5 },
      { name: 'Adajan', yield: '4–6%', appreciation: 'High', yieldMid: 5 },
      { name: 'Athwa', yield: '3.5–5%', appreciation: 'Stable', yieldMid: 4.2 },
      { name: 'Udhna', yield: '5–7%', appreciation: 'High', yieldMid: 6 },
      { name: 'Dumas Road', yield: '4.5–6%', appreciation: 'Med-High', yieldMid: 5.2 },
    ]
  },
  {
    id: 'chandigarh',
    name: 'Chandigarh',
    tier: 2,
    state: 'Punjab/Haryana',
    avgPriceSqft: '₹6,200',
    avgFlat2BHK: 4500000,
    yieldRange: '3.5–5.5%',
    yieldMid: 4.3,
    yieldMin: 3.5, yieldMax: 5.5,
    stampDuty: 5,
    registration: 1,
    loanRate: 8.5,
    appreciation: 6,
    demandLevel: 'Medium',
    demandNote: 'Planned city premium',
    avgRent2BHK: 18000,
    zones: [
      { name: 'Sector 8–11', yield: '3–5%', appreciation: 'Stable', yieldMid: 4 },
      { name: 'Mohali Aerocity', yield: '4.5–6.5%', appreciation: 'High', yieldMid: 5.5 },
      { name: 'Zirakpur', yield: '4.5–6%', appreciation: 'High', yieldMid: 5.2 },
      { name: 'Panchkula', yield: '4–5.5%', appreciation: 'Med-High', yieldMid: 4.7 },
      { name: 'IT Park', yield: '4–6%', appreciation: 'High', yieldMid: 5 },
      { name: 'New Chandigarh', yield: '4.5–7%', appreciation: 'Very High', yieldMid: 5.7 },
    ]
  }
];
